runtime: python
env: flex
entrypoint: bash -c 'python3 manage.py collectstatic --noinput && python3 manage.py migrate --noinput && gunicorn -b :$PORT ebdjango.wsgi'

# beta_settings:
#    cloud_sql_instances: orientami-assignment:us-central1:orientami-assignment-mysql


handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

runtime_config:
  python_version: 3
