version: 0.2

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - pip install --upgrade pip
      - echo "pip upgraded!"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Starting Migrations"
      - python manage.py migrate --noinput
      - echo "Starting Server"
      - python manage.py runserver > /dev/null 2>&1 &
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'